### ISSUE TITLE
mod_fcgid: stderr: PHP Deprecated:  Non-static method serendipity_event_freetag::makeURLTag

### ISSUE THREAD

**Issue by stevleibelt** [s9y/additional_plugins#41]
Hi there,

today was managing day for me and I found a lot of entries like the following in my error.log.

    mod_fcgid: stderr: PHP Deprecated:  Non-static method serendipity_event_freetag::makeURLTag
For the [freetag](https://github.com/s9y/additional_plugins/tree/master/serendipity_event_freetag) plugin, it was easy to fix this by simple adding "static" to the right place. It gave some instant freedom in my logs and it looks like it works as expected (so nothing was broken).
Before I start to make a pull request with my changes, I wanted to ask if there is any reason why the functions are not prefixed with "static" or "public/protected/private"?

FYI, I am running 1.7.8. on a php 5.6.2. system.

Kind regards,
Stev

**Comment by garvinhicking** [comment]
It seems you're not using the most recent freetag version? The the "static" keyword already exists? Current version is 3.63...

**Comment by mattsches** [comment]
The (only?) reason why the visibility of many properties and methods is not defined: nobody has done it yet ;) And it's still compatible with current PHP versions:

>The PHP 4 method of declaring a variable with the var keyword is still supported for compatibility reasons (as a synonym for the public keyword).

The same goes for methods, I guess.

**Comment by stevleibelt** [comment]
@garvinhicking 
you are right, my current version is 3.14. So it looks like also my upgrade mechanism [0] is not working as expected (since the page is displaying "nothing to update").
I had a look to the database table "pluginlist" and searched for "freetag" but I must say, I'm not deep enough into this to figure out why there are so many entries (with different path nams). But maybe this also indicates that my installation is broken :-(.
Anyways, since the problem is solved in version 3.63, I will close this issue. Thanks for the quick response.

@mattsches 
Thanks for the straight answere. PHP4 support is dropped, I would guess ;-). But with the [comment](https://github.com/s9y/Serendipity/issues/256#issuecomment-69459297) it sounds like a time consuming but doable task.

[0]
\<uri of my block>/serendipity_admin.php?serendipity[adminModule]=plugins&serendipity[adminAction]=addnew&serendipity[only_group]=UPGRADE&serendipity[type]=event

**Comment by ophian** [comment]
Is the Spartacus event plugin installed? It is a must have to do this...

**Comment by stevleibelt** [comment]
@ophian 
Yes ... bad side, it was available twice (two times available in database table "plugins"). As mention before, it looks like this installation (which is exists since 2008 and is now ported on the third server) is broken.
After removing the second spartacus plugin (after trying to figure out which is the good one ;-)), the freetag could be updated to the most recent version.
I will spend some more time with this installation so see what else is strange. Thanks for the hint, it was the right spot to look at :+1: .
